SKETCH = esp-visit-tracker.cpp

LIBS = libraries/BeamIntersectionTracker \
  ../vendor/ArduinoJson/src \
  ../vendor/arduinoWebSockets/src \
  /usr/local/lib/esp8266/libraries/ESP8266WiFi/src \
  /usr/local/lib/esp8266/libraries/Hash/src

UPLOAD_PORT = /dev/ttyUSB0

ESP_ROOT=/usr/local/lib/esp8266

include ../vendor/makeEspArduino/makeEspArduino.mk