SKETCH = esp-visit-tracker.cpp

LIBS = src \
  libraries/BeamIntersectionTracker \
  ../vendor/ArduinoJson/src \
  ../vendor/arduinoWebSockets/src \
  /usr/local/lib/esp8266/libraries/ESP8266WiFi/src \
  /usr/local/lib/esp8266/libraries/Hash/src \
  /usr/local/lib/esp8266/libraries/ESP8266httpUpdate/src \
  /usr/local/lib/esp8266/libraries/ESP8266HTTPClient/src

UPLOAD_PORT = /dev/ttyUSB0
UPLOAD_SPEED = 921600

ESP_ROOT=/usr/local/lib/esp8266

include ../vendor/makeEspArduino/makeEspArduino.mk